server:
  port: 9103
spring:
  application:
    name: microservice-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weixin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: yth13081606618
jwt:
  config:
    key: qpwoeirutyalskdjfhgzmxncvb123456
    ttl: 60000
