server:
  port: 9103
spring:
  application:
    name: microservice-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wechat?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: yth13081606618
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9101/eureka
  instance:
    hostname: localhost
jwt:
  config:
    key: qpwoeirutyalskdjfhgzmxncvb123
    ttl: 60000
