server:
  port: 7001
spring:
  application:
    name: microservice-eureka
eureka:
  instance:
    hostname: localhost
  client:
    registryFetchIntervalSeconds: 30 # 从Eureka服务端获取注册信息的间隔时间，单位为秒
    instanceInfoReplicationIntervalSeconds: 30 # 更新实例信息的变化到Eureka服务端的间隔时间，单位为秒
    initialInstanceInfoReplicationIntervalSeconds: 40 # 初始化实例信息到Eureka服务端的间隔时间，单位为秒
    eurekaServiceUrlPollIntervalSeconds: 300 # 轮询Eureka服务端地址更改的间隔时间，单位为秒。
    eurekaServerReadTimeoutSeconds: 8 # 读取Eureka Server信息的超时时间，单位为秒
    eurekaServerConnectTimeoutSeconds: 5 # 链接Eureka Server的超时时间，单位为秒
    eurekaServerTotalConnections: 50 # 从Eureka客户端到所有Eureka服务端的连接总数
    eurekaServerTotalConnectionsPerHost: 5 # 从Eureka客户端到每个Eureka服务端主机的连接总数
    eurekaConnectionIdleTimeoutSeconds: 30  # Eureka服务端连接的空闲关闭时间，单位为秒
    heartbeatExecutorThreadPoolSize: 2 # 心跳连接池的初始化线程数
    cacheRefreshExecutorExponentialBackOffBound: 10 # 心跳超时重试延迟时间的最大乘数值
    registerWithEureka: false # 是否要将自身的实例信息注册到Eureka服务端
    fetchRegistry: false # 是否从Eureka服务端获取注册信息
    # 指定注册中心
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/