server:
  port: 9103
spring:
  application:
    name: microservice-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weixin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: yth13081606618
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.1.76:9092         #Kafka的消息中间件服务器
          auto-create-topics: true        #如果设置为false,就不会自动创建Topic
      bindings:
        userChangeInput:
          destination: userTopic
          group: im
    bus:
      refresh:
        enabled: true
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.1.76:9411
jwt:
  config:
    key: qpwoeirutyalskdjfhgzmxncvb123456789
    ttl: 60000
management:
  endpoints:
    web:
      exposure:
        include: '*'
