server:
  port: 9102
spring:
  application:
    name: microservice-eureka
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false # 是否要将自身的实例信息注册到Eureka服务端
    fetchRegistry: false # 是否从Eureka服务端获取注册信息
    # 指定注册中心
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/